services:
  - type: web
    name: aditya-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --no-access-log
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
